format = """$username$status$hostname $directory$git_branch$character"""

# move the rest of the prompt to the right
right_format = """$all"""

[aws]
symbol = "  "

[buf]
disabled = true

[directory]
read_only = " 󰌾"
truncation_length = 255
truncate_to_repo = false
style = "blue"

[docker_context]
symbol = " "

[git_branch]
symbol = " "
style = 'purple'

[git_status]
stashed = ""

[git_commit]
tag_symbol = '  '

[golang]
symbol = " "
format = "[$symbol($version )]($style)"
style = 'cyan'

[hostname]
ssh_symbol = "@"
style = 'yellow'
format = '[$hostname]($style)'

[memory_usage]
symbol = "󰍛 "

[nix_shell]
disabled = true
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = "󰏗 "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = "󱘗 "

[username]
style_user = 'green'
style_root = 'red'
format = '[$user@]($style)'